name: "Argon Fan HAT"
description: "CPU temperature-based PWM fan control for the Argon Fan HAT."
version: "0.0.12"
slug: "argon_fan_hat"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-10
  - /dev/i2c-11
