name: "Argon Fan HAT"
description: "PWM fan control for the Argon Fan HAT."
version: "0.0.8"
slug: "argon_fan_hat"
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-10
  - /dev/i2c-11
options:
  fan_on_temp: 40
  sleep_interval: 10
schema:
  fan_on_temp: int
  sleep_interval: int
